type: QdrantDocumentStore
url: localhost
port: 6333
index: my_index
embeddings_dim: 768
similarity: dot_product
hnsw_config:
  m: 64
  ef_construct: 20
recreate_index: false    # set to true to generate new index
timeout: 60
