- name: AnswerParser
  params: {}
  type: AnswerParser
- name: custom-at-query-time
  params:
    output_parser: AnswerParser
    prompt: '{join(documents)}'
  type: PromptTemplate
- name: Reader
  params:
    default_prompt_template: custom-at-query-time
    model_kwargs:
      task_name: text2text-generation
    model_name_or_path: philschmid/bart-large-cnn-samsum
  type: PromptNode
