type: T5Reader
model_name_or_path:  "google/long-t5-tglobal-base"
top_k: 1 #Number of independently generated text to return
max_length: 180 #Maximum length of generated text
min_length: 10 #Minimum length of generated text
num_beams: 3 #Number of beams for beam search. 1 means no beam search
use_gpu: True
input_converter_tokenizer_max_len: 16300
input_converter_mode: "summarization" # "qa" or "translation" or "summarization"
