components:
- name: InMemoryDocumentStore
  params:
    use_bm25: true
  type: InMemoryDocumentStore
- name: Retriever
  params:
    document_store: InMemoryDocumentStore
    top_k: 30
  type: BM25Retriever
- name: Reranker
  params:
    batch_size: 32
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-6-v2
    top_k: 1
    use_gpu: false
  type: SentenceTransformersRanker
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
version: 1.21.0rc0
