components:
- name: Store
  params:
    host: localhost
    index: index-name
    port: 80
  type: ElasticsearchDocumentStore
- name: Retriever
  params:
    document_store: Store
    top_k: 10
  type: BM25Retriever
- name: Reranker
  params:
    batch_size: 32
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-12-v2
    top_k: 10
    use_gpu: true
  type: SentenceTransformersRanker
- name: Reader
  params:
    input_converter_tokenizer_max_len: 512
    max_length: 100
    min_length: 2
    model_name_or_path: Intel/fid_t5_large_nq
    num_beams: 3
    top_k: 2
    use_gpu: true
  type: FiDReader
pipelines:
- name: my_pipeline
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
  - inputs:
    - Reranker
    name: Reader
version: 1.12.2
