components:
- name: InMemoryDocumentStore
  params:
    use_bm25: true
    use_gpu: false
  type: InMemoryDocumentStore
- name: Retriever
  params:
    document_store: InMemoryDocumentStore
    top_k: 100
  type: BM25Retriever
- name: Reranker
  params:
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-12-v2
  type: SentenceTransformersRanker
- name: AnswerParser
  params: {}
  type: AnswerParser
- name: custom-at-query-time
  params:
    output_parser: AnswerParser
    prompt: '{join(documents)}'
  type: PromptTemplate
- name: Reader
  params:
    default_prompt_template: custom-at-query-time
    model_kwargs:
      task_name: text2text-generation
    model_name_or_path: philschmid/bart-large-cnn-samsum
  type: PromptNode
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
  - inputs:
    - Reranker
    name: Reader
version: 1.21.0rc0
