chat_model:
  generator_kwargs:
      model: meta-llama/Llama-3.2-11B-Vision-Instruct
      task: "image-to-text"
      generation_kwargs:
        max_new_tokens: 300
        do_sample: false
      huggingface_pipeline_kwargs:
        torch_dtype: torch.bfloat16
        trust_remote_code: true
  generator_class: fastrag.generators.llava.LlamaHFGenerator
tools:
  - type: doc_with_image
    params:
      name: "docRetriever"
      description: 'useful for when you need to retrieve images and text to answer questions. Use the following format: {{ "input": [your tool input here ] }}.'
      pipeline_or_yaml_file: "config/empty_ret_llama_32.yaml"
system_tools:
  - type: doc_with_image_index_from_provider
    params:
      name: "docIndex"
      pipeline_or_yaml_file: "config/empty_index_pipeline.yaml"
      tool_provider_name: docRetriever
